[package]
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
name = "firefox-deb"
version = "0.1.0"

[dependencies]
bzip2 = "0.3.2"
libc = "0.2.39"
reqwest = "0.8.5"
serde = "1.0.29"
serde_derive = "1.0.29"
structopt = "0.2.5"
tar = "0.4.14"
tempdir = "0.3.6"
